default_language_version:
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        files: '\.py$'
        args: [--enforce-all, --maxkb=200]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [ python ]