# Generated by Django 5.0.7 on 2024-07-23 15:21

import django.core.validators
from django.db import migrations, models

import evidenta.core.company.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=50)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                (
                    "company_identification_number",
                    models.CharField(
                        default=None,
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            evidenta.core.company.validators.CompanyIdentificationNumberValidator(),
                        ],
                    ),
                ),
                ("tax_identification_number", models.CharField(blank=True, default="", max_length=16, unique=True)),
                ("address_1", models.CharField(max_length=128)),
                ("address_2", models.CharField(blank=True, default="", max_length=128)),
                ("city", models.CharField(max_length=64)),
                ("zip_code", models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "company",
            },
        ),
    ]
